# overrides.yml
paths:
  # ───────────── custom metadata fields ─────────────
  /v1/customMetadataFields:
    post:
      x-fern-sdk-group-name: [customMetadataFields]
      x-fern-sdk-method-name: create
    get:
      x-fern-sdk-group-name: [customMetadataFields]
      x-fern-sdk-method-name: list
  /v1/customMetadataFields/{id}:
    patch:
      x-fern-sdk-group-name: [customMetadataFields]
      x-fern-sdk-method-name: update
    delete:
      x-fern-sdk-group-name: [customMetadataFields]
      x-fern-sdk-method-name: delete

  # ───────────────────── uploads ─────────────────────
  /api/v1/files/upload:
    post:
      x-fern-sdk-group-name: [files]
      x-fern-sdk-method-name: upload

  /api/v2/files/upload:
    post:
      x-fern-sdk-group-name: [beta, v2, files]
      x-fern-sdk-method-name: upload

  # ───────────────────── assets ─────────────────────
  /v1/files:
    get:
      x-fern-sdk-group-name: [assets]
      x-fern-sdk-method-name: list

  # ───────────────────── files (single + actions) ─────────────────────
  /v1/files/{fileId}/details:
    get:
      x-fern-sdk-group-name: [files]
      x-fern-sdk-method-name: get
    patch:
      x-fern-sdk-group-name: [files]
      x-fern-sdk-method-name: update

  /v1/files/{fileId}:
    delete:
      x-fern-sdk-group-name: [files]
      x-fern-sdk-method-name: delete

  /v1/files/copy:
    post:
      x-fern-sdk-group-name: [files]
      x-fern-sdk-method-name: copy

  /v1/files/move:
    post:
      x-fern-sdk-group-name: [files]
      x-fern-sdk-method-name: move

  /v1/files/rename:
    put:
      x-fern-sdk-group-name: [files]
      x-fern-sdk-method-name: rename

  # ───────────────────── files.bulk ─────────────────────
  /v1/files/batch/deleteByFileIds:
    post:
      x-fern-sdk-group-name: [files, bulk]
      x-fern-sdk-method-name: delete

  /v1/files/addTags:
    post:
      x-fern-sdk-group-name: [files, bulk]
      x-fern-sdk-method-name: addTags

  /v1/files/removeTags:
    post:
      x-fern-sdk-group-name: [files, bulk]
      x-fern-sdk-method-name: removeTags

  /v1/files/removeAITags:
    post:
      x-fern-sdk-group-name: [files, bulk]
      x-fern-sdk-method-name: removeAITags

  # ───────────────────── files.versions ─────────────────────
  /v1/files/{fileId}/versions:
    get:
      x-fern-sdk-group-name: [files, versions]
      x-fern-sdk-method-name: list

  /v1/files/{fileId}/versions/{versionId}:
    get:
      x-fern-sdk-group-name: [files, versions]
      x-fern-sdk-method-name: get
    delete:
      x-fern-sdk-group-name: [files, versions]
      x-fern-sdk-method-name: delete

  /v1/files/{fileId}/versions/{versionId}/restore:
    put:
      x-fern-sdk-group-name: [files, versions]
      x-fern-sdk-method-name: restore

  # ───────────────────── cache.invalidation ─────────────────────
  /v1/files/purge:
    post:
      x-fern-sdk-group-name: [cache, invalidation]
      x-fern-sdk-method-name: create

  /v1/files/purge/{requestId}:
    get:
      x-fern-sdk-group-name: [cache, invalidation]
      x-fern-sdk-method-name: get

  # ───────────────────── files.metadata ─────────────────────
  /v1/files/{fileId}/metadata:
    get:
      x-fern-sdk-group-name: [files, metadata]
      x-fern-sdk-method-name: get

  /v1/files/metadata:
    get:
      x-fern-sdk-group-name: [files, metadata]
      x-fern-sdk-method-name: getFromURL

  # ───────────────────── folders ─────────────────────
  /v1/folder:
    post:
      x-fern-sdk-group-name: [folders]
      x-fern-sdk-method-name: create
    delete:
      x-fern-sdk-group-name: [folders]
      x-fern-sdk-method-name: delete

  # bulk folder jobs directly under folders
  /v1/bulkJobs/copyFolder:
    post:
      x-fern-sdk-group-name: [folders]
      x-fern-sdk-method-name: copy

  /v1/bulkJobs/moveFolder:
    post:
      x-fern-sdk-group-name: [folders]
      x-fern-sdk-method-name: move

  /v1/bulkJobs/renameFolder:
    post:
      x-fern-sdk-group-name: [folders]
      x-fern-sdk-method-name: rename

  /v1/bulkJobs/{jobId}:
    get:
      x-fern-sdk-group-name: [folders, job]
      x-fern-sdk-method-name: get

  # ───────────────────── accounts ─────────────────────
  /v1/accounts/usage:
    get:
      x-fern-sdk-group-name: [accounts, usage]
      x-fern-sdk-method-name: get

  /v1/accounts/origins:
    get:
      x-fern-sdk-group-name: [accounts, origins]
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name: [accounts, origins]
      x-fern-sdk-method-name: create

  /v1/accounts/origins/{id}:
    get:
      x-fern-sdk-group-name: [accounts, origins]
      x-fern-sdk-method-name: get
    put:
      x-fern-sdk-group-name: [accounts, origins]
      x-fern-sdk-method-name: update
    delete:
      x-fern-sdk-group-name: [accounts, origins]
      x-fern-sdk-method-name: delete

  /v1/accounts/url-endpoints:
    get:
      x-fern-sdk-group-name: [accounts, urlEndpoints]
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name: [accounts, urlEndpoints]
      x-fern-sdk-method-name: create

  /v1/accounts/url-endpoints/{id}:
    get:
      x-fern-sdk-group-name: [accounts, urlEndpoints]
      x-fern-sdk-method-name: get
    put:
      x-fern-sdk-group-name: [accounts, urlEndpoints]
      x-fern-sdk-method-name: update
    delete:
      x-fern-sdk-group-name: [accounts, urlEndpoints]
      x-fern-sdk-method-name: delete
